linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

linters-settings:
  lll:
    line-length: 100
    tab-width: 4

issues:
  exclude-rules:
    - path: doc.go
      linters:
        - lll

    - source: ^func
      linters:
        - lll

    - source: ^var update =
      linters:
        - gochecknoglobals
